//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://walmart.com/", IsNullable=false)]
public partial class InventoryHeader {
    
    private InventoryHeaderVersion versionField;
    
    private System.DateTime feedDateField;
    
    private bool feedDateFieldSpecified;
    
    public InventoryHeader() {
        this.versionField = InventoryHeaderVersion.Item14;
    }
    
    /// <remarks/>
    public InventoryHeaderVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime feedDate {
        get {
            return this.feedDateField;
        }
        set {
            this.feedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedDateSpecified {
        get {
            return this.feedDateFieldSpecified;
        }
        set {
            this.feedDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://walmart.com/")]
public enum InventoryHeaderVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.4")]
    Item14,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public partial class Quantity {
    
    private UnitOfMeasurement unitField;
    
    private decimal amountField;
    
    /// <remarks/>
    public UnitOfMeasurement unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public enum UnitOfMeasurement {
    
    /// <remarks/>
    EACH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://walmart.com/", IsNullable=false)]
public partial class inventory {
    
    private string skuField;
    
    private Quantity quantityField;
    
    private int fulfillmentLagTimeField;
    
    /// <remarks/>
    public string sku {
        get {
            return this.skuField;
        }
        set {
            this.skuField = value;
        }
    }
    
    /// <remarks/>
    public Quantity quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public int fulfillmentLagTime {
        get {
            return this.fulfillmentLagTimeField;
        }
        set {
            this.fulfillmentLagTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://walmart.com/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://walmart.com/", IsNullable=false)]
public partial class InventoryFeed {
    
    private InventoryHeader inventoryHeaderField;
    
    private inventory[] itemsField;
    
    /// <remarks/>
    public InventoryHeader InventoryHeader {
        get {
            return this.inventoryHeaderField;
        }
        set {
            this.inventoryHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("inventory")]
    public inventory[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
