//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://walmart.com/", IsNullable=false)]
public partial class InventoryHeader {
    
    private InventoryHeaderVersion versionField;
    
    private System.DateTime feedDateField;
    
    private bool feedDateFieldSpecified;
    
    public InventoryHeader() {
        this.versionField = InventoryHeaderVersion.Item14;
    }
    
    /// <remarks/>
    public InventoryHeaderVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime feedDate {
        get {
            return this.feedDateField;
        }
        set {
            this.feedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedDateSpecified {
        get {
            return this.feedDateFieldSpecified;
        }
        set {
            this.feedDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://walmart.com/")]
public enum InventoryHeaderVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.4")]
    Item14,
}
