//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
[System.Xml.Serialization.XmlRootAttribute("PriceHeader", Namespace="http://walmart.com/", IsNullable=false)]
public partial class feedHeaderType {
    
    private feedHeaderTypeVersion versionField;
    
    private System.DateTime feedDateField;
    
    private bool feedDateFieldSpecified;
    
    /// <remarks/>
    public feedHeaderTypeVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime feedDate {
        get {
            return this.feedDateField;
        }
        set {
            this.feedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedDateSpecified {
        get {
            return this.feedDateFieldSpecified;
        }
        set {
            this.feedDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://walmart.com/")]
public enum feedHeaderTypeVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.5")]
    Item15,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public partial class priceDisplayCodes {
    
    private submapType submapTypeField;
    
    private bool submapTypeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public submapType submapType {
        get {
            return this.submapTypeField;
        }
        set {
            this.submapTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool submapTypeSpecified {
        get {
            return this.submapTypeFieldSpecified;
        }
        set {
            this.submapTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public enum submapType {
    
    /// <remarks/>
    CART,
    
    /// <remarks/>
    CHECKOUT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public partial class moneyType {
    
    private string currencyField;
    
    private decimal amountField;
    
    private string valueField;
    
    public moneyType() {
        this.currencyField = "USD";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("USD")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public partial class price {
    
    private moneyType valueField;
    
    /// <remarks/>
    public moneyType value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public partial class pricingType {
    
    private price currentPriceField;
    
    private priceType currentPriceTypeField;
    
    private bool currentPriceTypeFieldSpecified;
    
    private price comparisonPriceField;
    
    private priceDisplayCodes priceDisplayCodesField;
    
    private System.DateTime effectiveDateField;
    
    private bool effectiveDateFieldSpecified;
    
    private System.DateTime expirationDateField;
    
    private bool expirationDateFieldSpecified;
    
    /// <remarks/>
    public price currentPrice {
        get {
            return this.currentPriceField;
        }
        set {
            this.currentPriceField = value;
        }
    }
    
    /// <remarks/>
    public priceType currentPriceType {
        get {
            return this.currentPriceTypeField;
        }
        set {
            this.currentPriceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool currentPriceTypeSpecified {
        get {
            return this.currentPriceTypeFieldSpecified;
        }
        set {
            this.currentPriceTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public price comparisonPrice {
        get {
            return this.comparisonPriceField;
        }
        set {
            this.comparisonPriceField = value;
        }
    }
    
    /// <remarks/>
    public priceDisplayCodes priceDisplayCodes {
        get {
            return this.priceDisplayCodesField;
        }
        set {
            this.priceDisplayCodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime effectiveDate {
        get {
            return this.effectiveDateField;
        }
        set {
            this.effectiveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool effectiveDateSpecified {
        get {
            return this.effectiveDateFieldSpecified;
        }
        set {
            this.effectiveDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime expirationDate {
        get {
            return this.expirationDateField;
        }
        set {
            this.expirationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expirationDateSpecified {
        get {
            return this.expirationDateFieldSpecified;
        }
        set {
            this.expirationDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public enum priceType {
    
    /// <remarks/>
    BASE,
    
    /// <remarks/>
    REDUCED,
    
    /// <remarks/>
    CLEARANCE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
public partial class itemIdentifierType {
    
    private string itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sku")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/")]
[System.Xml.Serialization.XmlRootAttribute("Price", Namespace="http://walmart.com/", IsNullable=false)]
public partial class itemPriceType {
    
    private itemIdentifierType itemIdentifierField;
    
    private pricingType[] pricingListField;
    
    /// <remarks/>
    public itemIdentifierType itemIdentifier {
        get {
            return this.itemIdentifierField;
        }
        set {
            this.itemIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("pricing", IsNullable=false)]
    public pricingType[] pricingList {
        get {
            return this.pricingListField;
        }
        set {
            this.pricingListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://walmart.com/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://walmart.com/", IsNullable=false)]
public partial class PriceFeed {
    
    private feedHeaderType priceHeaderField;
    
    private itemPriceType[] priceField;
    
    /// <remarks/>
    public feedHeaderType PriceHeader {
        get {
            return this.priceHeaderField;
        }
        set {
            this.priceHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Price")]
    public itemPriceType[] Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
}
