//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://walmart.com/mp/v3/orders")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://walmart.com/mp/v3/orders", IsNullable=false)]
public partial class orderShipment {
    
    private shippingLineType[] orderLinesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("orderLine", IsNullable=false)]
    public shippingLineType[] orderLines {
        get {
            return this.orderLinesField;
        }
        set {
            this.orderLinesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public partial class shippingLineType {
    
    private string lineNumberField;
    
    private shipLineStatusType[] orderLineStatusesField;
    
    /// <remarks/>
    public string lineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("orderLineStatus", IsNullable=false)]
    public shipLineStatusType[] orderLineStatuses {
        get {
            return this.orderLineStatusesField;
        }
        set {
            this.orderLineStatusesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public partial class shipLineStatusType {
    
    private orderLineStatusValueType statusField;
    
    private quantityType statusQuantityField;
    
    private trackingInfoType trackingInfoField;
    
    /// <remarks/>
    public orderLineStatusValueType status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public quantityType statusQuantity {
        get {
            return this.statusQuantityField;
        }
        set {
            this.statusQuantityField = value;
        }
    }
    
    /// <remarks/>
    public trackingInfoType trackingInfo {
        get {
            return this.trackingInfoField;
        }
        set {
            this.trackingInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public enum orderLineStatusValueType {
    
    /// <remarks/>
    Created,
    
    /// <remarks/>
    Acknowledged,
    
    /// <remarks/>
    Shipped,
    
    /// <remarks/>
    Cancelled,
    
    /// <remarks/>
    Refund,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public partial class quantityType {
    
    private string unitOfMeasurementField;
    
    private string amountField;
    
    /// <remarks/>
    public string unitOfMeasurement {
        get {
            return this.unitOfMeasurementField;
        }
        set {
            this.unitOfMeasurementField = value;
        }
    }
    
    /// <remarks/>
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public partial class carrierNameType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("carrier", typeof(carrierType))]
    [System.Xml.Serialization.XmlElementAttribute("otherCarrier", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public enum carrierType {
    
    /// <remarks/>
    UPS,
    
    /// <remarks/>
    USPS,
    
    /// <remarks/>
    FedEx,
    
    /// <remarks/>
    Airborne,
    
    /// <remarks/>
    OnTrac,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public partial class trackingInfoType {
    
    private System.DateTime shipDateTimeField;
    
    private carrierNameType carrierNameField;
    
    private shippingMethodCodeType methodCodeField;
    
    private string trackingNumberField;
    
    private string trackingURLField;
    
    /// <remarks/>
    public System.DateTime shipDateTime {
        get {
            return this.shipDateTimeField;
        }
        set {
            this.shipDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public carrierNameType carrierName {
        get {
            return this.carrierNameField;
        }
        set {
            this.carrierNameField = value;
        }
    }
    
    /// <remarks/>
    public shippingMethodCodeType methodCode {
        get {
            return this.methodCodeField;
        }
        set {
            this.methodCodeField = value;
        }
    }
    
    /// <remarks/>
    public string trackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string trackingURL {
        get {
            return this.trackingURLField;
        }
        set {
            this.trackingURLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walmart.com/mp/v3/orders")]
public enum shippingMethodCodeType {
    
    /// <remarks/>
    Standard,
    
    /// <remarks/>
    Express,
    
    /// <remarks/>
    OneDay,
    
    /// <remarks/>
    Freight,
    
    /// <remarks/>
    WhiteGlove,
}
